import { getCategory } from "@/app/api/categoryApi";
import ChannelsList from "@/components/ChannelsList/ChannelsList";
import RecList from "@/components/RecListMain/RecListMain";
import SwiperMainComponent from "@/components/SwiperMainComponent/SwiperMainComponent";
import { Metadata } from "next";
import styles from "./index.module.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function searchCategory(query: string) {
  const res = await fetch(
    `${process.env.BASE_URL}/channels/search?query=${query}&page=0&limit=31`
  );
  if (!res.ok) {
    throw new Error("Failed to fetch data");
  }
  return res.json();
}

export default async function HomePage({
  searchParams,
}: {
  searchParams?: { term?: string };
}) {
  const query = searchParams?.term || "";
  const AccurateCategory = await searchCategory(query);
  const categoryList = await getCategory();

  return (
    <div className={styles.section}>
      <h2 className={styles.title}>Поиск телеграм каналов по {query}</h2>
      <SwiperMainComponent count={3} data={categoryList} />
      <div className={styles.channel_section}>
        <ChannelsList path="channel" data={AccurateCategory} />
      </div>
      <RecList />
    </div>
  );
}
