export {default as SearchIcon} from './SearchIcon.svg'
export {default as AddSquare} from './Add Square.svg'
export {default as ArrowBack} from './Arrow-Back.svg'
export {default as ArrowForward} from './Arrow-forward.svg'
export {default as ForwardButton} from './ForwardButton.svg'
export {default as BackButton} from './BackButton.svg'
