import ChannelsList from "@/components/ChannelsList/ChannelsList";
import { Metadata } from "next";
import styles from "./index.module.scss";
import AdvertisementCard from "@/components/Cards/AdvertisementCard/AdvertisementCard";
import CardInner from "@/components/Cards/CardInner/CardInner";
import SwiperMainComponent from "@/components/SwiperMainComponent/SwiperMainComponent";
import { getCategory } from "@/app/api/categoryApi";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getAcuurateCategory(translit_name: string) {
  const res = await fetch(
    `https://test-api-teleshtorm.teleshtorm.org/categories/channels?page=0&limit=31&category_translit=${translit_name}`
  );
  if (!res.ok) {
    throw new Error("Failed to fetch data");
  }
  return res.json();
}

export default async function Categories({
  params,
}: {
  params: { translit_name: string };
}) {
  const translit_name = params.translit_name;
  const AccurateCategory = await getAcuurateCategory(translit_name);
  const categoryList = await getCategory();

  return (
    <div className={styles.section}>
      <h2 className={styles.title}>
        Каталог телеграм каналов в категории: {translit_name}
      </h2>
      <SwiperMainComponent count={3} data={categoryList} main={false} />
      <div className={styles.channel_section}>
        <h3 className={styles.subtitle}>Телеграмм каналы</h3>
        <ChannelsList data={AccurateCategory} />
      </div>
    </div>
  );
}
