name: CI\CD PROD
on:
  push:
    branches: [ "main" ]

  workflow_dispatch:
  
jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script_stop: true
        script: |
                cd /home/teleshtorm_reps/teleshtorm_front
                git pull https://${{ secrets.GH_TOKEN }}@github.com/Delitel-WEB/teleshtorm_front.git main
                git checkout main
                docker build --build-arg BASE_URL=${{secrets.API_URL_PROD}} --build-arg NEXT_PUBLIC_SITE_URL=${{secrets.PUBLIC_SITE_URL_PROD}} --build-arg TELEGRAM_CHANNEL=${{secrets.TELEGRAM_CHANNEL_PROD}} -t teleshtorm_front:prod .
                cd /home/Teleshtorm
                docker-compose stop teleshtorm_front_prod
                docker-compose rm -f teleshtorm_front_prod
                docker-compose up -d teleshtorm_front_prod