name: 'Commit Message Check'
on:
  pull_request:
    branches: ["main", "dev"]

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^(feat|fix|docs|style|refactor|test|chore|perf|build|ci|revert|release)(\([a-zA-Z0-9_-]+\))?: .{1,72}(\n\n.*)?$'
          flags: 'gm'
          error: 'Сообщение коммита не соответствует формату Conventional Commits.'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GH_TOKEN }}
          excludeTitle: 'true'

